# Generated by Django 5.1.4 on 2025-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='75000', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='Paris', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(blank=True, default={'lat': 48.8566, 'lng': 2.3522}, help_text='Coordinates in {lat: float, lng: float} format', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='France', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, default='Île-de-France', max_length=100, null=True),
        ),
    ]
