# Generated by Django 5.1.4 on 2025-01-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('contact_info', models.JSONField(default=dict)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('social_media_links', models.JSONField(default=dict)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('reputation_score', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('languages', models.ManyToManyField(to='users.language')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
                ('social_media_platforms', models.ManyToManyField(to='users.socialmediaplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('PROFILE_VERIFIED', 'Profile vérifié'), ('NEW_MESSAGE', 'Nouveau message'), ('NEW_REVIEW', 'Nouvel avis'), ('LISTING_APPROVED', 'Annonce approuvée'), ('PROFILE_VIEWED', 'Profil consulté'), ('REPUTATION_CHANGE', 'Changement de réputation')], max_length=50)),
                ('related_object_id', models.PositiveIntegerField(null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('related_object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['notification_type'], name='users_notif_notific_af6ddd_idx'), models.Index(fields=['read', 'created_at'], name='users_notif_read_c60db7_idx')],
            },
        ),
    ]
