# Generated by Django 5.1.4 on 2025-01-05 10:26

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_verified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfos',
            options={'verbose_name': 'Informations de contact', 'verbose_name_plural': 'Informations de contact'},
        ),
        migrations.AddField(
            model_name='contactinfos',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='contactinfos',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format international requis (ex: +33612345678 pour la France)', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='contactinfos',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format international requis (ex: +33612345678 pour la France)', max_length=128, null=True, region=None),
        ),
    ]
