# Generated by Django 5.1.4 on 2025-01-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contactinfos_options_contactinfos_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfos',
            options={'verbose_name': '2. Informations de contact', 'verbose_name_plural': '2. Informations de contact'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name_plural': '3. Langues'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '1. Profiles utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='socialinks',
            options={'verbose_name_plural': '3. Liens sociaux'},
        ),
    ]
