# Generated by Django 5.1.4 on 2025-01-04 18:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('location', '0003_alter_location_coordinates'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL full-text search vector', null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listing_lis_search__201935_gin'),
        ),
    ]
