# Generated by Django 5.1.4 on 2025-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
