# Generated by Django 5.1.4 on 2025-03-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('location', '0003_alter_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='location.location'),
        ),
    ]
