# Generated by Django 5.1.4 on 2025-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_search_vector_and_more'),
        ('location', '0003_alter_location_coordinates'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_lis_search__201935_gin',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['search_vector'], name='listing_lis_search__900708_idx'),
        ),
    ]
