# Generated by Django 5.1.4 on 2025-01-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listing_listing_lis_search__201935_gin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_title',
            new_name='title',
        ),
    ]
