# Generated by Django 5.1.4 on 2025-01-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_rename_listing_title_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='profile',
            new_name='owner',
        ),
    ]
