# Generated by Django 5.1.4 on 2025-01-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_rename_profile_listing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='profile',
        ),
    ]
