# Generated by Django 5.1.4 on 2025-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_rename_owner_listing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.CharField(blank=True, default='Pamoja', max_length=200, null=True),
        ),
    ]
