# Generated by Django 5.1.4 on 2025-01-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_remove_customtag_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytics',
            options={'verbose_name_plural': '5. Statistiques'},
        ),
        migrations.AlterModelOptions(
            name='businesshours',
            options={'verbose_name_plural': "8. Horaires d'ouverture"},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name_plural': '6. Informations de contact'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '3. Annonces'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-is_primary', '-uploaded_at'], 'verbose_name_plural': '9. Medias'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '4. Avis'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': '7. Réseaux sociaux'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': '2. Sous-categories'},
        ),
    ]
