# Generated by Django 5.1 on 2024-09-21 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('loc', models.CharField(blank=True, max_length=50, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('postal', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone_info', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('page_requested', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_time_view', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_time_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
