# Generated by Django 5.0 on 2024-01-05 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(null=True, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='securitypreference',
            name='backup_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='securitypreference',
            name='backup_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='securitypreference',
            name='last_security_review',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='securitypreference',
            name='password_expiry_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='securitypreference',
            name='security_level',
            field=models.CharField(
                choices=[
                    ('LOW', 'Basique'),
                    ('MEDIUM', 'Standard'),
                    ('HIGH', 'Renforcé'),
                    ('CUSTOM', 'Personnalisé')
                ],
                default='MEDIUM',
                max_length=10
            ),
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(
                    choices=[
                        ('EMAIL', 'Email de secours'),
                        ('PHONE', 'Téléphone de secours'),
                        ('QUESTIONS', 'Questions de sécurité'),
                        ('BACKUP_CODES', 'Codes de secours')
                    ],
                    max_length=20
                )),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityquestion',
            index=models.Index(fields=['user', 'is_active'], name='auth_securi_user_id_active_idx'),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['user', 'is_used'], name='auth_backup_user_id_used_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverymethod',
            index=models.Index(fields=['user', 'method_type', 'is_active'], name='auth_recove_user_method_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='auth_passwo_user_id_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='backupcode',
            constraint=models.UniqueConstraint(fields=['user', 'code'], name='unique_user_backup_code'),
        ),
    ] 