# Generated by Django 5.1.4 on 2025-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'Simple utilisateur'), ('Provider', 'Prestataire'), ('Administrator', 'Administrateur'), ('Moderator', 'Modérateur'), ('Staff', 'Personnel')], default='User', help_text="Rôle de l'utilisateur", max_length=15),
        ),
    ]
